CATEGORIES = ["Rings", "Necklaces", "Earrings", "Bracelets", "Bangles",
              "Pendants", "Anklets", "Sets"]

BANNERS = [
    {"title": "New Gold Collection", "subtitle": "Pure 22K BIS Hallmarked Gold", "cta": "Shop Now"},
    {"title": "Diamond Sale",        "subtitle": "Up to 40% off certified diamonds", "cta": "Explore"},
    {"title": "Silver Essentials",   "subtitle": "925 Sterling Silver – starting ₹999", "cta": "Discover"},
]

# ── Per-product image URLs — each product has its own dedicated image ──────────
IMG = {
    "eternal_solitaire_ring":   "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSYqzeKLYbAWI9lUkmxi8iomUr5jaPvmCChUUfARSb_11AReivDlHVQjbFz2PvceCT82dBn65W4AYR0UkQ436YMRr9t9EB9KgYfaxkjdlgAqbWfBmvwXE4RnDgiM3OpOzb8jG3J0A&usqp=CAc",
    "lotus_temple_ring":        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRoQQY2SS4a_V1WJVlPDwMW2Ufb4QZxrGeSRzD0qmILTg&s=10",
    "moonlit_rose_gold_band":   "https://maioradiamonds.in/cdn/shop/files/MD-R11779_3_1800x.webp?v=1777269296",
    "vintage_emerald_ring":     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOs2vsxRj_Xr0wiyWWaXaeheD_cg2aXLt5hbZF2cmJIA&s=10",
    "rani_haar_necklace":       "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRss-HkMXamxlUygDYz3hZm1qqOYCSZsiqqimmP9trUYcSKmWng_A_sJs4_1XQGIk6oPL96rNq4uPlFHAKtmdatwT7HdJqrID8B4d84spXgW33fGd6mBPnwZRa_8Ri3vJXGvQcTtr0&usqp=CAc",
    "diamond_tennis_necklace":  "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRC4pTT6fsSf4tO08XVxe12fWCJzRDkfEEsn5OGoep5VQ58WuucQnYcqmWoFREwsVtX8uL_0RO7aybLdDzYdCCsJ9OIz_WgAAwOknTAdupeE61idckcWvYXGEl0TKfL0pqOecXftw&usqp=CAc",
    "dainty_pearl_strand":      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpFEKcrdNHp_hWSZbCcF2DbmcredONMyPTnn75mcMP7w&s=10",
    "kundan_choker_set":        "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTJB4gQ0KaTTrCvHqUwkeQR6tLSYE0gOG9Lreb3W6MH5Arc5ikJ3p2oOMJGN-YholWuaM1IWuAuYKAjJ_MtAwANGPQsCMFKKz7B53s1u6p8ZjbO1jcF4gTatnOblLuMk00j6kuN3Jz7fQ&usqp=CAc",
    "jhumka_classic_gold":      "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRR5oT7NJHJ2N7W9YBcx0rAxRMeIIPhj0rsU3gIRxve-Edq9-eeJSD3ox7ZQRWP8bUPG78Cn87FXJGG9gzwTmyukFdRFShkJzvDbekxB4ngBxFIYXAsSU76tFtpZOjQ2MKwM8JCvGc&usqp=CAc",
    "diamond_stud_solitaire":   "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTwMapj7scfp-7sbsfUhokm-HutqS4dRoX4_SotOcJJPQZTjXPKGGdyes3b5dUFX_sMo2Zl3FODR0hg7qhdkU8G9lkj3-1lGat8P1eVwmAOw7gqmIN68K7EErIAeEWpNuMcoBj9Sr0&usqp=CAc",
    "meenakari_chandbali":      "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSeSadMi70Vilyfbdy70-JEo-VEBw7BcIm21AHPtIzimonNOn5quao844yM5zz-H_JmZok8S3At-qr-eqLFy426SLkolK4q-aYUvpbqe8omGnOVuG6EDfNDjA-hLtGqKyDkSS1vv3k&usqp=CAc",
    "silver_hoop_earrings":     "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRIA7XbpLVG4RX8MRvSCfrLozz0OaDajbqOqNguaAQtvtaTyeZTt-X5nSP9IE6VuZ49Iy2ClPMlmLLU_QipKM15QIqgBVkgfnE3RK-bm-B2OITyLISiOSj_Spx5YxKD6ie0vx0glNc&usqp=CAc",
    "gold_charm_bracelet":      "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR4lsTFKd0CRLfPHZodPxMzCUXHelzYG2qdWV46TFjNTuBHQQ8WeCnvFQOVqB0ICOXJ1TbKL4DHRPhnTHz1sFL-Wak6bNwcWErzx1o_6ODq3DZMbiTnjBI6bq4F7vnWH0T2DbEn1w&usqp=CAc",
    "diamond_tennis_bracelet":  "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTTYxPELxV0B9vIFDOgAiR1usJQpgEpaCjTDBi26bcaRYGPIonLf0EM9EbC2PWmrfHRu4Ig5gSzDVxE83ekRqy-PtXxFKo7tVC4gu_dNRdCPGwEHt8pEl0GGnhmSry0TALxYTWjkg&usqp=CAc",
    "boho_silver_cuff":         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWmLDNbX7yZmhI-MlKBvH8Q2r_aVAHD6tmgOV3MmKulA&s",
    "antique_gold_bangle_set":  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqKihpPCPWCAdlDuJbanevFcLoIs2Zmi88bVdqfXtHpg&s=10",
    "laakh_bangle":             "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtjE_mfKdMxjZuNXOt89WrPB6iV8q85HZfvZQqjtcBUw&s=10",
    "ganesha_pendant":          "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcR3Bv6ApuVc55W4k_qxAKdKz097zpY3QoYIa_EJEnFqnZdgr44dr0Ex-UuAfcLx9VDU1YGfti0_33bl01w5MiZZw8cmhoNNozRQKp09aHNtJ41MoQKwPwJ6tJXQzBx5rANnFAin8A&usqp=CAc",
    "evil_eye_pendant":         "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQL07FZU-UZfryN9VjFfu3ageh8RKqacQUJfA7PanMS48Ycn9HQsn5daTmZa3WRwBcJx1uHEUVSP9A2jxrwtHl1eWu8Ooxor6LNrvnEE0tFSOYnxzu3TrFqCfgOedI18tTPOUQpSQ&usqp=CAc",
    "silver_payal":             "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQE7gf0qGpIsG1VCVe3ictsbS2xRgcwf6djijsrClrdXWmnkyiMSprQGi72KpTHFcZj8WsuiBwHB5ow3baxX-EgWFG24SwWe5VTtg_Tu3cgZzCPtMjctCu0KKirfpekpgRBVod8kqpD_Q&usqp=CAc",
    "bridal_kundan_set":        "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ0jsvngQM5PvckFyE6ylfUeTELbqMQMmu0_kVXks6VV-g5w3lzBpUKpq6ps7gmEtvGmCjULdh5bQLOBtNv27Fk1ynduz4OrAo5CjHQBoIL9nC8tqZaDx2ROSbEY_f_Q1ZAGC1Vg7UIyNE&usqp=CAc",
    "diamond_solitaire_set":    "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSE-BTL80qBjNaMSWMRUm7iw4j2WKdP-it1Edtkpb2e4sWuLP5lbi2x5rRkTL5U6J76bsOws2TlF8rS_TVPa9WXpbuZaKvPQ7SsKVAK6kUZ5YMIQplb0WKoViSqCQl3Gr9NtH4PeN0&usqp=CAc",
}

PRODUCTS = [
    # ── RINGS ──────────────────────────────────────────────────────────────────
    {
        "id": "r001", "name": "Eternal Solitaire Ring",
        "category": "Rings", "material": "Diamond · 18K Gold",
        "price": 45999, "mrp": 65000, "rating": 4.8, "reviews": 312,
        "emoji": "💍", "new": False, "featured": True,
        "image": IMG["eternal_solitaire_ring"],
        "weight": "3.2g", "purity": "18K Gold (75%)",
        "occasion": "Engagement, Anniversary",
        "description": "A timeless solitaire set in 18K gold, featuring a GIA-certified round brilliant diamond. Crafted for the moment that lasts forever.",
    },
    {
        "id": "r002", "name": "Lotus Temple Ring",
        "category": "Rings", "material": "22K Gold",
        "price": 18500, "mrp": 22000, "rating": 4.6, "reviews": 198,
        "emoji": "🌸", "new": True, "featured": True,
        "image": IMG["lotus_temple_ring"],
        "weight": "4.8g", "purity": "22K Gold (91.6%)",
        "occasion": "Wedding, Traditional",
        "description": "An intricate lotus motif ring in 22K BIS hallmarked gold — rooted in tradition, designed for the modern bride.",
    },
    {
        "id": "r003", "name": "Moonlit Rose Gold Band",
        "category": "Rings", "material": "Rose Gold",
        "price": 12999, "mrp": 15500, "rating": 4.5, "reviews": 145,
        "emoji": "🌙", "new": True, "featured": False,
        "image": IMG["moonlit_rose_gold_band"],
        "weight": "2.8g", "purity": "18K Rose Gold",
        "occasion": "Casual, Gift",
        "description": "A sleek rose gold band with a delicate moonstone inlay — effortlessly wearable from dawn to dusk.",
    },
    {
        "id": "r004", "name": "Vintage Emerald Ring",
        "category": "Rings", "material": "Silver · Emerald",
        "price": 8999, "mrp": 11000, "rating": 4.7, "reviews": 87,
        "emoji": "💚", "new": False, "featured": False,
        "image": IMG["vintage_emerald_ring"],
        "weight": "5g", "purity": "925 Sterling Silver",
        "occasion": "Cocktail, Party",
        "description": "Deep Colombian emerald set in oxidised sterling silver. A statement piece with old-world glamour.",
    },
    # ── NECKLACES ──────────────────────────────────────────────────────────────
    {
        "id": "n001", "name": "Rani Haar Gold Necklace",
        "category": "Necklaces", "material": "22K Gold",
        "price": 78500, "mrp": 92000, "rating": 4.9, "reviews": 421,
        "emoji": "📿", "new": False, "featured": True,
        "image": IMG["rani_haar_necklace"],
        "weight": "32g", "purity": "22K Gold (91.6%)",
        "occasion": "Wedding, Bridal",
        "description": "A regal Rani Haar in 22K gold — a symbol of grace and prosperity that has adorned brides for generations.",
    },
    {
        "id": "n002", "name": "Diamond Tennis Necklace",
        "category": "Necklaces", "material": "Diamond · Platinum",
        "price": 125000, "mrp": 160000, "rating": 4.9, "reviews": 68,
        "emoji": "✨", "new": False, "featured": True,
        "image": IMG["diamond_tennis_necklace"],
        "weight": "15g", "purity": "Platinum 950",
        "occasion": "Evening, Gala",
        "description": "Forty-two round-cut IGI certified diamonds set in platinum. The ultimate expression of understated luxury.",
    },
    {
        "id": "n003", "name": "Dainty Pearl Strand",
        "category": "Necklaces", "material": "Silver · Pearl",
        "price": 5999, "mrp": 8000, "rating": 4.4, "reviews": 203,
        "emoji": "🤍", "new": True, "featured": False,
        "image": IMG["dainty_pearl_strand"],
        "weight": "8g", "purity": "925 Sterling Silver",
        "occasion": "Office, Casual",
        "description": "Freshwater pearls on a delicate silver chain — a timeless piece for everyday elegance.",
    },
    {
        "id": "n004", "name": "Kundan Choker Set",
        "category": "Necklaces", "material": "Kundan · Gold Plated",
        "price": 4999, "mrp": 6500, "rating": 4.6, "reviews": 334,
        "emoji": "🟡", "new": False, "featured": True,
        "image": IMG["kundan_choker_set"],
        "weight": "45g", "purity": "Gold Plated",
        "occasion": "Festive, Wedding",
        "description": "Vibrant Kundan work on a gold-plated base — a celebration of India's finest jewellery craft.",
    },
    # ── EARRINGS ───────────────────────────────────────────────────────────────
    {
        "id": "e001", "name": "Jhumka Classic Gold",
        "category": "Earrings", "material": "22K Gold",
        "price": 15800, "mrp": 18500, "rating": 4.8, "reviews": 567,
        "emoji": "⭕", "new": False, "featured": True,
        "image": IMG["jhumka_classic_gold"],
        "weight": "8.4g", "purity": "22K Gold (91.6%)",
        "occasion": "Wedding, Festive",
        "description": "The timeless jhumka — reimagined with fine filigree in 22K gold. Where heritage meets heirloom.",
    },
    {
        "id": "e002", "name": "Diamond Stud Solitaire",
        "category": "Earrings", "material": "Diamond · 18K Gold",
        "price": 22500, "mrp": 30000, "rating": 4.7, "reviews": 289,
        "emoji": "💫", "new": False, "featured": False,
        "image": IMG["diamond_stud_solitaire"],
        "weight": "1.8g", "purity": "18K White Gold",
        "occasion": "All occasions",
        "description": "0.5ct each, GIA certified diamond studs in 18K white gold — the jewellery wardrobe essential.",
    },
    {
        "id": "e003", "name": "Meenakari Chandbali",
        "category": "Earrings", "material": "Gold Plated · Meenakari",
        "price": 3299, "mrp": 4500, "rating": 4.5, "reviews": 412,
        "emoji": "🌈", "new": True, "featured": True,
        "image": IMG["meenakari_chandbali"],
        "weight": "12g", "purity": "Gold Plated Brass",
        "occasion": "Festive, Ethnic",
        "description": "Hand-painted meenakari chandbali — each piece unique, each colour a story told in enamel.",
    },
    {
        "id": "e004", "name": "Silver Hoop Earrings",
        "category": "Earrings", "material": "Silver",
        "price": 1999, "mrp": 2800, "rating": 4.3, "reviews": 678,
        "emoji": "🔵", "new": False, "featured": False,
        "image": IMG["silver_hoop_earrings"],
        "weight": "4g", "purity": "925 Sterling Silver",
        "occasion": "Casual, Office",
        "description": "Minimalist 925 silver hoops — designed to go with everything, from Monday meetings to Friday nights.",
    },
    # ── BRACELETS ──────────────────────────────────────────────────────────────
    {
        "id": "b001", "name": "Gold Charm Bracelet",
        "category": "Bracelets", "material": "18K Gold",
        "price": 28000, "mrp": 34000, "rating": 4.6, "reviews": 156,
        "emoji": "💛", "new": False, "featured": True,
        "image": IMG["gold_charm_bracelet"],
        "weight": "7g", "purity": "18K Gold (75%)",
        "occasion": "Gift, Anniversary",
        "description": "A charm bracelet in 18K gold — collect moments, one charm at a time.",
    },
    {
        "id": "b002", "name": "Diamond Tennis Bracelet",
        "category": "Bracelets", "material": "Diamond · White Gold",
        "price": 89000, "mrp": 110000, "rating": 4.9, "reviews": 43,
        "emoji": "💎", "new": False, "featured": False,
        "image": IMG["diamond_tennis_bracelet"],
        "weight": "9g", "purity": "18K White Gold",
        "occasion": "Evening, Special",
        "description": "A continuous line of channel-set round diamonds in 18K white gold — effortless luxury on your wrist.",
    },
    {
        "id": "b003", "name": "Boho Silver Cuff",
        "category": "Bracelets", "material": "Silver",
        "price": 2499, "mrp": 3500, "rating": 4.4, "reviews": 290,
        "emoji": "🌿", "new": True, "featured": False,
        "image": IMG["boho_silver_cuff"],
        "weight": "18g", "purity": "925 Sterling Silver",
        "occasion": "Casual, Beach",
        "description": "Hammered sterling silver cuff with tribal motif — made for wanderers and free spirits.",
    },
    # ── BANGLES ────────────────────────────────────────────────────────────────
    {
        "id": "bg001", "name": "Antique Gold Bangle Set",
        "category": "Bangles", "material": "22K Gold",
        "price": 52000, "mrp": 62000, "rating": 4.7, "reviews": 234,
        "emoji": "🔮", "new": False, "featured": True,
        "image": IMG["antique_gold_bangle_set"],
        "weight": "24g (set of 4)", "purity": "22K Gold (91.6%)",
        "occasion": "Bridal, Wedding",
        "description": "Set of 4 antique-finish bangles in 22K gold — each bangle tells a story of timeless Indian craftsmanship.",
    },
    {
        "id": "bg002", "name": "Laakh Bangle with Mirror",
        "category": "Bangles", "material": "Laakh · Gold Plated",
        "price": 1599, "mrp": 2200, "rating": 4.3, "reviews": 445,
        "emoji": "🎪", "new": False, "featured": False,
        "image": IMG["laakh_bangle"],
        "weight": "35g", "purity": "Gold Plated",
        "occasion": "Festive, Traditional",
        "description": "Handcrafted laakh bangles with mirror work — vibrant, bold, and rooted in Rajasthani tradition.",
    },
    # ── PENDANTS ───────────────────────────────────────────────────────────────
    {
        "id": "p001", "name": "Ganesha Gold Pendant",
        "category": "Pendants", "material": "22K Gold",
        "price": 8900, "mrp": 11000, "rating": 4.8, "reviews": 678,
        "emoji": "🌟", "new": False, "featured": True,
        "image": IMG["ganesha_pendant"],
        "weight": "4g", "purity": "22K Gold (91.6%)",
        "occasion": "Religious, Gift",
        "description": "A beautifully detailed Ganesha pendant in 22K gold — a blessing to carry close to your heart.",
    },
    {
        "id": "p002", "name": "Evil Eye Diamond Pendant",
        "category": "Pendants", "material": "Diamond · Silver",
        "price": 6999, "mrp": 9500, "rating": 4.6, "reviews": 523,
        "emoji": "🔵", "new": True, "featured": True,
        "image": IMG["evil_eye_pendant"],
        "weight": "2.5g", "purity": "925 Sterling Silver",
        "occasion": "Everyday, Gift",
        "description": "A dainty evil eye pendant set with a centre diamond — for protection and modern-day magic.",
    },
    # ── ANKLETS ────────────────────────────────────────────────────────────────
    {
        "id": "a001", "name": "Traditional Silver Payal",
        "category": "Anklets", "material": "Silver",
        "price": 2899, "mrp": 3800, "rating": 4.5, "reviews": 312,
        "emoji": "🌙", "new": False, "featured": False,
        "image": IMG["silver_payal"],
        "weight": "20g (pair)", "purity": "925 Sterling Silver",
        "occasion": "Traditional, Wedding",
        "description": "Classic ghungroo payal in pure silver — the sweet sound of tradition with every step.",
    },
    # ── SETS ───────────────────────────────────────────────────────────────────
    {
        "id": "s001", "name": "Bridal Kundan Set",
        "category": "Sets", "material": "Kundan · Gold Plated",
        "price": 12999, "mrp": 18000, "rating": 4.8, "reviews": 267,
        "emoji": "👑", "new": False, "featured": True,
        "image": IMG["bridal_kundan_set"],
        "weight": "120g (full set)", "purity": "Gold Plated",
        "occasion": "Bridal, Wedding",
        "description": "Complete bridal set — necklace, earrings, maang tikka, and bangles in ornate Kundan work.",
    },
    {
        "id": "s002", "name": "Diamond Solitaire Set",
        "category": "Sets", "material": "Diamond · 18K White Gold",
        "price": 185000, "mrp": 220000, "rating": 4.9, "reviews": 34,
        "emoji": "💠", "new": False, "featured": True,
        "image": IMG["diamond_solitaire_set"],
        "weight": "18g", "purity": "18K White Gold",
        "occasion": "Engagement, Anniversary",
        "description": "Matching solitaire ring, earrings, and pendant in 18K white gold with GIA certified diamonds.",
    },
]
